services:
  front:
    build: ./frontend
    develop:
      watch:
        - action: sync
          path: ./components
          target: /src/app/components
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:4200
  back:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5434:5432
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
